# Generated by Django 4.0.2 on 2022-04-27 09:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cop', '0004_remove_orders_tags_product_tags'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orders',
            old_name='staus',
            new_name='status',
        ),
    ]
